apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alertmanager-httproute.yaml
  - alertmanager-sealedsecret.yaml
  - blackbox-exporter-helmrelease.yaml
  - grafana-httproute.yaml
  - grafana-pvc.yaml
  - grafana-replicationdestination.yaml
  - grafana-replicationsource.yaml
  - grafana-restic-sealedsecret.yaml
  - grafana-sealedsecret.yaml
  - kube-prometheus-stack-helmrelease.yaml
  - prometheus-helmrepository.yaml
  - prometheus-httproute.yaml
  - prometheus-pvc.yaml
  - prometheus-replicationdestination.yaml
  - prometheus-replicationsource.yaml
  - prometheus-restic-sealedsecret.yaml