apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: container
resources:
  - buildkit-amd64-deployment.yaml
  - buildkit-amd64-pvc.yaml
  - buildkit-amd64-service.yaml
  - buildkit-amd64-tcproute.yaml
  - buildkit-arm64-deployment.yaml
  - buildkit-arm64-pvc.yaml
  - buildkit-arm64-service.yaml
  - buildkit-arm64-tcproute.yaml